/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rpn;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RpnEvaluatorTest {

    @Test
    void evaluateSimpleExpression() {
        assertEquals(14, new RpnEvaluator().evaluate("3 4 + 2 *"));
    }

    @Test
    void evaluatesDivision() {
        RpnEvaluator evaluator = new RpnEvaluator();
        assertEquals(2, evaluator.evaluate("8 4 /"));
    }
}
